We scrapping of HTML table

Website: https://www.skysports.com/premier-league-table/2019

In [1]:
import pandas as pd
from bs4 import BeautifulSoup
import requests
import numpy as np

In [2]:
#FIRST WE SCRAPE 2019/2020 TABLE

In [3]:

url = "https://www.skysports.com/premier-league-table/2019"

In [4]:
r = requests.get(url)
soup = BeautifulSoup(r.text, 'html.parser')

In [5]:
l = soup.find('table', class_="standing-table__table")

In [6]:
print(l)

<table class="standing-table__table callfn" data-fn="table-sorter-lite" data-lite="true">
<caption class="standing-table__caption">
    Premier League 2019/20  </caption>
<colgroup class="standing-table__cols">
<col class="standing-table__cell standing-table__col1"/>
<col class="standing-table__cell standing-table__col2 standing-table__cell--name"/>
<col class="standing-table__cell standing-table__col3"/>
<col class="standing-table__cell standing-table__col4 is-hidden--bp35"/>
<col class="standing-table__cell standing-table__col5 is-hidden--bp35"/>
<col class="standing-table__cell standing-table__col6 is-hidden--bp35"/>
<col class="standing-table__cell standing-table__col7 is-hidden--bp35"/>
<col class="standing-table__cell standing-table__col8 is-hidden--bp35"/>
<col class="standing-table__cell standing-table__col9"/>
<col class="standing-table__cell standing-table__col10"/>
<col class="standing-table__cell standing-table__col11 is-hidden--bp15 is-hidden--bp35 is-hidden"/>
</colgroup>
<thead>
<tr class="standing-table__row">
<th class="standing-table__cell standing-table__header-cell" data-index="0" data-label="pos" title="Position">#</th>
<th class="standing-table__cell standing-table__header-cell standing-table__cell--name" data-index="1" title="Team">Team</th>
<th class="standing-table__cell standing-table__header-cell" data-index="2" data-label="pld" title="Played">Pl</th>
<th class="standing-table__cell standing-table__header-cell is-hidden--bp35" data-index="3" data-label="w" title="Won">W</th>
<th class="standing-table__cell standing-table__header-cell is-hidden--bp35" data-index="4" data-label="d">D</th>
<th class="standing-table__cell standing-table__header-cell is-hidden--bp35" data-index="5" data-label="l">L</th>
<th class="standing-table__cell standing-table__header-cell is-hidden--bp35" data-index="6" data-label="f">F</th>
<th class="standing-table__cell standing-table__header-cell is-hidden--bp35" data-index="7" data-label="a">A</th>
<th class="standing-table__cell standing-table__header-cell" data-index="8" data-label="gd">GD</th>
<th class="standing-table__cell standing-table__header-cell" data-index="9" data-label="pts" data-sort-value="use-attribute">Pts</th>
<th class="standing-table__cell standing-table__header-cell is-hidden--bp15 is-hidden--bp35 is-hidden" data-index="10" data-sort-value="use-attribute">Last 6</th>
</tr>
</thead>
<tbody>
<tr class="standing-table__row" data-item-id="155">
<td class="standing-table__cell">1</td>
<td class="standing-table__cell standing-table__cell--name" data-long-name="Liverpool" data-short-name="Liverpool">
<a class="standing-table__cell--name-link" href="/liverpool">Liverpool</a>
</td>
<td class="standing-table__cell">38</td>
<td class="standing-table__cell is-hidden--bp35">32</td>
<td class="standing-table__cell is-hidden--bp35">3</td>
<td class="standing-table__cell is-hidden--bp35">3</td>
<td class="standing-table__cell is-hidden--bp35">85</td>
<td class="standing-table__cell is-hidden--bp35">33</td>
<td class="standing-table__cell">52</td>
<td class="standing-table__cell" data-sort-value="1">99</td>
<td class="standing-table__cell is-hidden--bp15 is-hidden--bp35 is-hidden" data-sort-value="0">
</td>
</tr>
<tr class="standing-table__row" data-item-id="345">
<td class="standing-table__cell">2</td>
<td class="standing-table__cell standing-table__cell--name" data-long-name="Manchester City" data-short-name="Manchester City">
<a class="standing-table__cell--name-link" href="/manchester-city">Manchester City</a>
</td>
<td class="standing-table__cell">38</td>
<td class="standing-table__cell is-hidden--bp35">26</td>
<td class="standing-table__cell is-hidden--bp35">3</td>
<td class="standing-table__cell is-hidden--bp35">9</td>
<td class="standing-table__cell is-hidden--bp35">102</td>
<td class="standing-table__cell is-hidden--bp35">35</td>
<td class="standing-table__cell">67</td>
<td class="standing-table__cell" data-sort-value="2">81</td>
<td class="standing-table__cell is-hidden--bp15 is-hidden--bp35 is-hidden" data-sort-value="0">
</td>
</tr>
<tr class="standing-table__row" data-item-id="210">
<td class="standing-table__cell">3</td>
<td class="standing-table__cell standing-table__cell--name" data-long-name="Manchester United" data-short-name="Manchester United">
<a class="standing-table__cell--name-link" href="/manchester-united">Manchester United</a>
</td>
<td class="standing-table__cell">38</td>
<td class="standing-table__cell is-hidden--bp35">18</td>
<td class="standing-table__cell is-hidden--bp35">12</td>
<td class="standing-table__cell is-hidden--bp35">8</td>
<td class="standing-table__cell is-hidden--bp35">66</td>
<td class="standing-table__cell is-hidden--bp35">36</td>
<td class="standing-table__cell">30</td>
<td class="standing-table__cell" data-sort-value="3">66</td>
<td class="standing-table__cell is-hidden--bp15 is-hidden--bp35 is-hidden" data-sort-value="0">
</td>
</tr>
<tr class="standing-table__row" data-item-id="524">
<td class="standing-table__cell">4</td>
<td class="standing-table__cell standing-table__cell--name" data-long-name="Chelsea" data-short-name="Chelsea">
<a class="standing-table__cell--name-link" href="/chelsea">Chelsea</a>
</td>
<td class="standing-table__cell">38</td>
<td class="standing-table__cell is-hidden--bp35">20</td>
<td class="standing-table__cell is-hidden--bp35">6</td>
<td class="standing-table__cell is-hidden--bp35">12</td>
<td class="standing-table__cell is-hidden--bp35">69</td>
<td class="standing-table__cell is-hidden--bp35">54</td>
<td class="standing-table__cell">15</td>
<td class="standing-table__cell" data-sort-value="4">66</td>
<td class="standing-table__cell is-hidden--bp15 is-hidden--bp35 is-hidden" data-sort-value="0">
</td>
</tr>
<tr class="standing-table__row standing-table__row--divider" data-item-id="152">
<td class="standing-table__cell">5</td>
<td class="standing-table__cell standing-table__cell--name" data-long-name="Leicester City" data-short-name="Leicester City">
<a class="standing-table__cell--name-link" href="/leicester-city">Leicester City</a>
</td>
<td class="standing-table__cell">38</td>
<td class="standing-table__cell is-hidden--bp35">18</td>
<td class="standing-table__cell is-hidden--bp35">8</td>
<td class="standing-table__cell is-hidden--bp35">12</td>
<td class="standing-table__cell is-hidden--bp35">67</td>
<td class="standing-table__cell is-hidden--bp35">41</td>
<td class="standing-table__cell">26</td>
<td class="standing-table__cell" data-sort-value="5">62</td>
<td class="standing-table__cell is-hidden--bp15 is-hidden--bp35 is-hidden" data-sort-value="0">
</td>
</tr>
<tr class="standing-table__row standing-table__row--divider" data-item-id="608">
<td class="standing-table__cell">6</td>
<td class="standing-table__cell standing-table__cell--name" data-long-name="Tottenham Hotspur" data-short-name="Tottenham Hotspur">
<a class="standing-table__cell--name-link" href="/tottenham-hotspur">Tottenham Hotspur</a>
</td>
<td class="standing-table__cell">38</td>
<td class="standing-table__cell is-hidden--bp35">16</td>
<td class="standing-table__cell is-hidden--bp35">11</td>
<td class="standing-table__cell is-hidden--bp35">11</td>
<td class="standing-table__cell is-hidden--bp35">61</td>
<td class="standing-table__cell is-hidden--bp35">47</td>
<td class="standing-table__cell">14</td>
<td class="standing-table__cell" data-sort-value="6">59</td>
<td class="standing-table__cell is-hidden--bp15 is-hidden--bp35 is-hidden" data-sort-value="0">
</td>
</tr>
<tr class="standing-table__row" data-item-id="206">
<td class="standing-table__cell">7</td>
<td class="standing-table__cell standing-table__cell--name" data-long-name="Wolverhampton Wanderers" data-short-name="Wolverhampton Wanderers">
<a class="standing-table__cell--name-link" href="/wolverhampton-wanderers">Wolverhampton Wanderers</a>
</td>
<td class="standing-table__cell">38</td>
<td class="standing-table__cell is-hidden--bp35">15</td>
<td class="standing-table__cell is-hidden--bp35">14</td>
<td class="standing-table__cell is-hidden--bp35">9</td>
<td class="standing-table__cell is-hidden--bp35">51</td>
<td class="standing-table__cell is-hidden--bp35">40</td>
<td class="standing-table__cell">11</td>
<td class="standing-table__cell" data-sort-value="7">59</td>
<td class="standing-table__cell is-hidden--bp15 is-hidden--bp35 is-hidden" data-sort-value="0">
</td>
</tr>
<tr class="standing-table__row" data-item-id="413">
<td class="standing-table__cell">8</td>
<td class="standing-table__cell standing-table__cell--name" data-long-name="Arsenal" data-short-name="Arsenal">
<a class="standing-table__cell--name-link" href="/arsenal">Arsenal</a>
</td>
<td class="standing-table__cell">38</td>
<td class="standing-table__cell is-hidden--bp35">14</td>
<td class="standing-table__cell is-hidden--bp35">14</td>
<td class="standing-table__cell is-hidden--bp35">10</td>
<td class="standing-table__cell is-hidden--bp35">56</td>
<td class="standing-table__cell is-hidden--bp35">48</td>
<td class="standing-table__cell">8</td>
<td class="standing-table__cell" data-sort-value="8">56</td>
<td class="standing-table__cell is-hidden--bp15 is-hidden--bp35 is-hidden" data-sort-value="0">
</td>
</tr>
<tr class="standing-table__row" data-item-id="444">
<td class="standing-table__cell">9</td>
<td class="standing-table__cell standing-table__cell--name" data-long-name="Sheffield United" data-short-name="Sheffield United">
<a class="standing-table__cell--name-link" href="/sheffield-united">Sheffield United</a>
</td>
<td class="standing-table__cell">38</td>
<td class="standing-table__cell is-hidden--bp35">14</td>
<td class="standing-table__cell is-hidden--bp35">12</td>
<td class="standing-table__cell is-hidden--bp35">12</td>
<td class="standing-table__cell is-hidden--bp35">39</td>
<td class="standing-table__cell is-hidden--bp35">39</td>
<td class="standing-table__cell">0</td>
<td class="standing-table__cell" data-sort-value="9">54</td>
<td class="standing-table__cell is-hidden--bp15 is-hidden--bp35 is-hidden" data-sort-value="0">
</td>
</tr>
<tr class="standing-table__row" data-item-id="160">
<td class="standing-table__cell">10</td>
<td class="standing-table__cell standing-table__cell--name" data-long-name="Burnley" data-short-name="Burnley">
<a class="standing-table__cell--name-link" href="/burnley">Burnley</a>
</td>
<td class="standing-table__cell">38</td>
<td class="standing-table__cell is-hidden--bp35">15</td>
<td class="standing-table__cell is-hidden--bp35">9</td>
<td class="standing-table__cell is-hidden--bp35">14</td>
<td class="standing-table__cell is-hidden--bp35">43</td>
<td class="standing-table__cell is-hidden--bp35">50</td>
<td class="standing-table__cell">-7</td>
<td class="standing-table__cell" data-sort-value="10">54</td>
<td class="standing-table__cell is-hidden--bp15 is-hidden--bp35 is-hidden" data-sort-value="0">
</td>
</tr>
<tr class="standing-table__row" data-item-id="392">
<td class="standing-table__cell">11</td>
<td class="standing-table__cell standing-table__cell--name" data-long-name="Southampton" data-short-name="Southampton">
<a class="standing-table__cell--name-link" href="/southampton">Southampton</a>
</td>
<td class="standing-table__cell">38</td>
<td class="standing-table__cell is-hidden--bp35">15</td>
<td class="standing-table__cell is-hidden--bp35">7</td>
<td class="standing-table__cell is-hidden--bp35">16</td>
<td class="standing-table__cell is-hidden--bp35">51</td>
<td class="standing-table__cell is-hidden--bp35">60</td>
<td class="standing-table__cell">-9</td>
<td class="standing-table__cell" data-sort-value="11">52</td>
<td class="standing-table__cell is-hidden--bp15 is-hidden--bp35 is-hidden" data-sort-value="0">
</td>
</tr>
<tr class="standing-table__row" data-item-id="229">
<td class="standing-table__cell">12</td>
<td class="standing-table__cell standing-table__cell--name" data-long-name="Everton" data-short-name="Everton">
<a class="standing-table__cell--name-link" href="/everton">Everton</a>
</td>
<td class="standing-table__cell">38</td>
<td class="standing-table__cell is-hidden--bp35">13</td>
<td class="standing-table__cell is-hidden--bp35">10</td>
<td class="standing-table__cell is-hidden--bp35">15</td>
<td class="standing-table__cell is-hidden--bp35">44</td>
<td class="standing-table__cell is-hidden--bp35">56</td>
<td class="standing-table__cell">-12</td>
<td class="standing-table__cell" data-sort-value="12">49</td>
<td class="standing-table__cell is-hidden--bp15 is-hidden--bp35 is-hidden" data-sort-value="0">
</td>
</tr>
<tr class="standing-table__row" data-item-id="409">
<td class="standing-table__cell">13</td>
<td class="standing-table__cell standing-table__cell--name" data-long-name="Newcastle United" data-short-name="Newcastle United">
<a class="standing-table__cell--name-link" href="/newcastle-united">Newcastle United</a>
</td>
<td class="standing-table__cell">38</td>
<td class="standing-table__cell is-hidden--bp35">11</td>
<td class="standing-table__cell is-hidden--bp35">11</td>
<td class="standing-table__cell is-hidden--bp35">16</td>
<td class="standing-table__cell is-hidden--bp35">38</td>
<td class="standing-table__cell is-hidden--bp35">58</td>
<td class="standing-table__cell">-20</td>
<td class="standing-table__cell" data-sort-value="13">44</td>
<td class="standing-table__cell is-hidden--bp15 is-hidden--bp35 is-hidden" data-sort-value="0">
</td>
</tr>
<tr class="standing-table__row" data-item-id="234">
<td class="standing-table__cell">14</td>
<td class="standing-table__cell standing-table__cell--name" data-long-name="Crystal Palace" data-short-name="Crystal Palace">
<a class="standing-table__cell--name-link" href="/crystal-palace">Crystal Palace</a>
</td>
<td class="standing-table__cell">38</td>
<td class="standing-table__cell is-hidden--bp35">11</td>
<td class="standing-table__cell is-hidden--bp35">10</td>
<td class="standing-table__cell is-hidden--bp35">17</td>
<td class="standing-table__cell is-hidden--bp35">31</td>
<td class="standing-table__cell is-hidden--bp35">50</td>
<td class="standing-table__cell">-19</td>
<td class="standing-table__cell" data-sort-value="14">43</td>
<td class="standing-table__cell is-hidden--bp15 is-hidden--bp35 is-hidden" data-sort-value="0">
</td>
</tr>
<tr class="standing-table__row" data-item-id="212">
<td class="standing-table__cell">15</td>
<td class="standing-table__cell standing-table__cell--name" data-long-name="Brighton and Hove Albion" data-short-name="Brighton and Hove Albion">
<a class="standing-table__cell--name-link" href="/brighton-and-hove-albion">Brighton and Hove Albion</a>
</td>
<td class="standing-table__cell">38</td>
<td class="standing-table__cell is-hidden--bp35">9</td>
<td class="standing-table__cell is-hidden--bp35">14</td>
<td class="standing-table__cell is-hidden--bp35">15</td>
<td class="standing-table__cell is-hidden--bp35">39</td>
<td class="standing-table__cell is-hidden--bp35">54</td>
<td class="standing-table__cell">-15</td>
<td class="standing-table__cell" data-sort-value="15">41</td>
<td class="standing-table__cell is-hidden--bp15 is-hidden--bp35 is-hidden" data-sort-value="0">
</td>
</tr>
<tr class="standing-table__row" data-item-id="367">
<td class="standing-table__cell">16</td>
<td class="standing-table__cell standing-table__cell--name" data-long-name="West Ham United" data-short-name="West Ham United">
<a class="standing-table__cell--name-link" href="/west-ham-united">West Ham United</a>
</td>
<td class="standing-table__cell">38</td>
<td class="standing-table__cell is-hidden--bp35">10</td>
<td class="standing-table__cell is-hidden--bp35">9</td>
<td class="standing-table__cell is-hidden--bp35">19</td>
<td class="standing-table__cell is-hidden--bp35">49</td>
<td class="standing-table__cell is-hidden--bp35">62</td>
<td class="standing-table__cell">-13</td>
<td class="standing-table__cell" data-sort-value="16">39</td>
<td class="standing-table__cell is-hidden--bp15 is-hidden--bp35 is-hidden" data-sort-value="0">
</td>
</tr>
<tr class="standing-table__row" data-item-id="238">
<td class="standing-table__cell">17</td>
<td class="standing-table__cell standing-table__cell--name" data-long-name="Aston Villa" data-short-name="Aston Villa">
<a class="standing-table__cell--name-link" href="/aston-villa">Aston Villa</a>
</td>
<td class="standing-table__cell">38</td>
<td class="standing-table__cell is-hidden--bp35">9</td>
<td class="standing-table__cell is-hidden--bp35">8</td>
<td class="standing-table__cell is-hidden--bp35">21</td>
<td class="standing-table__cell is-hidden--bp35">41</td>
<td class="standing-table__cell is-hidden--bp35">67</td>
<td class="standing-table__cell">-26</td>
<td class="standing-table__cell" data-sort-value="17">35</td>
<td class="standing-table__cell is-hidden--bp15 is-hidden--bp35 is-hidden" data-sort-value="0">
</td>
</tr>
<tr class="standing-table__row standing-table__row--divider" data-item-id="333">
<td class="standing-table__cell">18</td>
<td class="standing-table__cell standing-table__cell--name" data-long-name="Bournemouth" data-short-name="Bournemouth">
<a class="standing-table__cell--name-link" href="/bournemouth">Bournemouth</a>
</td>
<td class="standing-table__cell">38</td>
<td class="standing-table__cell is-hidden--bp35">9</td>
<td class="standing-table__cell is-hidden--bp35">7</td>
<td class="standing-table__cell is-hidden--bp35">22</td>
<td class="standing-table__cell is-hidden--bp35">40</td>
<td class="standing-table__cell is-hidden--bp35">65</td>
<td class="standing-table__cell">-25</td>
<td class="standing-table__cell" data-sort-value="18">34</td>
<td class="standing-table__cell is-hidden--bp15 is-hidden--bp35 is-hidden" data-sort-value="0">
</td>
</tr>
<tr class="standing-table__row" data-item-id="508">
<td class="standing-table__cell">19</td>
<td class="standing-table__cell standing-table__cell--name" data-long-name="Watford" data-short-name="Watford">
<a class="standing-table__cell--name-link" href="/watford">Watford</a>
</td>
<td class="standing-table__cell">38</td>
<td class="standing-table__cell is-hidden--bp35">8</td>
<td class="standing-table__cell is-hidden--bp35">10</td>
<td class="standing-table__cell is-hidden--bp35">20</td>
<td class="standing-table__cell is-hidden--bp35">36</td>
<td class="standing-table__cell is-hidden--bp35">64</td>
<td class="standing-table__cell">-28</td>
<td class="standing-table__cell" data-sort-value="19">34</td>
<td class="standing-table__cell is-hidden--bp15 is-hidden--bp35 is-hidden" data-sort-value="0">
</td>
</tr>
<tr class="standing-table__row" data-item-id="290">
<td class="standing-table__cell">20</td>
<td class="standing-table__cell standing-table__cell--name" data-long-name="Norwich City" data-short-name="Norwich City">
<a class="standing-table__cell--name-link" href="/norwich-city">Norwich City</a>
</td>
<td class="standing-table__cell">38</td>
<td class="standing-table__cell is-hidden--bp35">5</td>
<td class="standing-table__cell is-hidden--bp35">6</td>
<td class="standing-table__cell is-hidden--bp35">27</td>
<td class="standing-table__cell is-hidden--bp35">26</td>
<td class="standing-table__cell is-hidden--bp35">75</td>
<td class="standing-table__cell">-49</td>
<td class="standing-table__cell" data-sort-value="20">21</td>
<td class="standing-table__cell is-hidden--bp15 is-hidden--bp35 is-hidden" data-sort-value="0">
</td>
</tr>
</tbody>
</table>

In [7]:
league_tb = []
for team in l.find_all('tbody'):
    rows = team.find_all('tr')
    for row in rows:
        pl_team = row.find('td', class_='standing-table__cell standing-table__cell--name').text.strip()
        pl_points = row.find_all('td', class_='standing-table__cell')[9].text
        pl = row.find_all('td', class_='standing-table__cell')[2].text
        w = row.find_all('td', class_='standing-table__cell')[3].text
        d = row.find_all('td', class_='standing-table__cell')[4].text
        l = row.find_all('td', class_='standing-table__cell')[5].text
        f = row.find_all('td', class_='standing-table__cell')[6].text
        a = row.find_all('td', class_='standing-table__cell')[7].text
        gd = row.find_all('td', class_='standing-table__cell')[8].text
        #print(pl_team, pl_points)
        
        lister = { #creating a dict with data scrapped
            'Clubs':pl_team,
            'Pl':pl,
            'W':w,
            'D':d,
            'L':l,
            'F':f,
            'A':a,
            'GD':gd,
            'Pts': pl_points
            
            
            
            
        }
        
        league_tb.append(lister) #adding it to list
         
table = pd.DataFrame(league_tb)

In [8]:
table

                       Clubs  Pl   W   D   L    F   A   GD Pts
0                  Liverpool  38  32   3   3   85  33   52  99
1            Manchester City  38  26   3   9  102  35   67  81
2          Manchester United  38  18  12   8   66  36   30  66
3                    Chelsea  38  20   6  12   69  54   15  66
4             Leicester City  38  18   8  12   67  41   26  62
5          Tottenham Hotspur  38  16  11  11   61  47   14  59
6    Wolverhampton Wanderers  38  15  14   9   51  40   11  59
7                    Arsenal  38  14  14  10   56  48    8  56
8           Sheffield United  38  14  12  12   39  39    0  54
9                    Burnley  38  15   9  14   43  50   -7  54
10               Southampton  38  15   7  16   51  60   -9  52
11                   Everton  38  13  10  15   44  56  -12  49
12          Newcastle United  38  11  11  16   38  58  -20  44
13            Crystal Palace  38  11  10  17   31  50  -19  43
14  Brighton and Hove Albion  38   9  14  15   39  54  -15  41
15           West Ham United  38  10   9  19   49  62  -13  39
16               Aston Villa  38   9   8  21   41  67  -26  35
17               Bournemouth  38   9   7  22   40  65  -25  34
18                   Watford  38   8  10  20   36  64  -28  34
19              Norwich City  38   5   6  27   26  75  -49  21

In [9]:
#WE NOW SCRAPE 2020/2021

In [10]:
urlbase = 'https://www.skysports.com/premier-league-table/2020'

In [11]:
p = requests.get(urlbase)
souper = BeautifulSoup(p.text, 'html.parser')

In [12]:
pl = souper.find('table', class_="standing-table__table")

In [13]:
leaguex = []
for team in pl.find_all('tbody'):
    rows = team.find_all('tr')
    for row in rows:
        pl_team = row.find('td', class_='standing-table__cell standing-table__cell--name').text.strip()
        pl_points = row.find_all('td', class_='standing-table__cell')[9].text
        pl = row.find_all('td', class_='standing-table__cell')[2].text
        w = row.find_all('td', class_='standing-table__cell')[3].text
        d = row.find_all('td', class_='standing-table__cell')[4].text
        l = row.find_all('td', class_='standing-table__cell')[5].text
        f = row.find_all('td', class_='standing-table__cell')[6].text
        a = row.find_all('td', class_='standing-table__cell')[7].text
        gd = row.find_all('td', class_='standing-table__cell')[8].text
        #print(pl_team, pl_points)
        
        lista = { #creating a dict with data scrapped
            'Clubs':pl_team,
            'Pl':pl,
            'W':w,
            'D':d,
            'L':l,
            'F':f,
            'A':a,
            'GD':gd,
            'Pts': pl_points
            
            
            
            
        }
        leaguex.append(lista)

In [14]:
pd.DataFrame(leaguex)

                       Clubs Pl  W  D  L   F   A  GD Pts
0                    Everton  5  4  1  0  14   7   7  13
1                  Liverpool  6  4  1  1  15  14   1  13
2                Aston Villa  5  4  0  1  12   5   7  12
3               Leeds United  6  3  1  2  12   9   3  10
4             Crystal Palace  6  3  1  2   8   9  -1  10
5                    Chelsea  6  2  3  1  13   9   4   9
6             Leicester City  5  3  0  2  12   8   4   9
7                    Arsenal  5  3  0  2   8   6   2   9
8    Wolverhampton Wanderers  5  3  0  2   5   7  -2   9
9          Tottenham Hotspur  5  2  2  1  15   8   7   8
10           West Ham United  6  2  2  2  12   8   4   8
11           Manchester City  5  2  2  1   8   8   0   8
12               Southampton  5  2  1  2   8   9  -1   7
13          Newcastle United  5  2  1  2   7   9  -2   7
14         Manchester United  5  2  1  2   9  12  -3   7
15  Brighton and Hove Albion  5  1  1  3   9  11  -2   4
16      West Bromwich Albion  5  0  2  3   5  13  -8   2
17                   Burnley  4  0  1  3   3   8  -5   1
18          Sheffield United  6  0  1  5   3   9  -6   1
19                    Fulham  6  0  1  5   5  14  -9   1